/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author CAMARGO
 */
public class Calculo extends javax.swing.JFrame {

    /**
     * Creates new form Calculo
     */
    public Calculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Numero1 = new javax.swing.JLabel();
        Numero2 = new javax.swing.JLabel();
        Resultado = new javax.swing.JLabel();
        Soma = new javax.swing.JButton();
        Novo = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        Comparação = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        Mutiplicação = new javax.swing.JButton();
        Subtração = new javax.swing.JButton();
        Divisão = new javax.swing.JButton();
        N1 = new javax.swing.JTextField();
        N2 = new javax.swing.JTextField();
        Resultadado = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton9.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Numero1.setText("Numero 1");

        Numero2.setText("Numero 2");

        Resultado.setText("Resultados");

        Soma.setText("+");
        Soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SomaActionPerformed(evt);
            }
        });

        Novo.setText("Novo");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        Comparação.setText("Comparação");
        Comparação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComparaçãoActionPerformed(evt);
            }
        });

        Sair.setText("Sair");

        Mutiplicação.setText("*");
        Mutiplicação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MutiplicaçãoActionPerformed(evt);
            }
        });

        Subtração.setText("-");
        Subtração.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtraçãoActionPerformed(evt);
            }
        });

        Divisão.setText("/");
        Divisão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisãoActionPerformed(evt);
            }
        });

        N1.setText("jTextField1");

        N2.setText("jTextField1");

        Resultadado.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Soma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Resultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Resultadado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Mutiplicação)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Subtração)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Divisão))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Numero2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(N2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Numero1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(N1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Novo)
                .addGap(18, 18, 18)
                .addComponent(Limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(Sair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Comparação)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero1)
                    .addComponent(N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero2)
                    .addComponent(N2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Resultado)
                    .addComponent(Resultadado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Soma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mutiplicação)
                    .addComponent(Subtração)
                    .addComponent(Divisão))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Novo)
                    .addComponent(Limpar)
                    .addComponent(Comparação)
                    .addComponent(Sair))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComparaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComparaçãoActionPerformed
    
      
        
    }//GEN-LAST:event_ComparaçãoActionPerformed

    private void SomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SomaActionPerformed
    float x, y, z;
    String r;  // R string para receber valor 
       
       
    x  = Integer.parseInt( N1.getText()); //Mesclando o Campo com a variável
    y  = Integer.parseInt( N2.getText()); 
       
    z = x + y;//operação  
    r = String.valueOf(z); // passando a variável para String para que o campo de texto seja aceito 
    Resultado.setText(r);// Camppo de resposta recebendo valor 

        
    }//GEN-LAST:event_SomaActionPerformed

    private void MutiplicaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MutiplicaçãoActionPerformed
       
        float x, y, z;
    String r;  // R string para receber valor 
       
       
    x  = Integer.parseInt( N1.getText()); //Mesclando o Campo com a variável
    y  = Integer.parseInt( N2.getText()); 
       
    z = x * y;//operação  
    r = String.valueOf(z); // passando a variável para String para que o campo de texto seja aceito 
    Resultado.setText(r);// Camppo de resposta recebendo valor 
        
    }//GEN-LAST:event_MutiplicaçãoActionPerformed

    private void SubtraçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtraçãoActionPerformed
       
        int x, y, z;
    String r;  // R string para receber valor 
       
       
    x  = Integer.parseInt( N1.getText()); //Mesclando o Campo com a variável
    y  = Integer.parseInt( N2.getText()); 
       
    z = x - y;//operação  
    r = String.valueOf(z); // passando a variável para String para que o campo de texto seja aceito 
    Resultado.setText(r);// Camppo de resposta recebendo valor 
        
    }//GEN-LAST:event_SubtraçãoActionPerformed

    private void DivisãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisãoActionPerformed
        
        int x, y, z;
    String r;  // R string para receber valor 
       
       
    x  = Integer.parseInt( N1.getText()); //Mesclando o Campo com a variável
    y  = Integer.parseInt( N2.getText()); 
       
    z = x / y;//operação  
    r = String.valueOf(z); // passando a variável para String para que o campo de texto seja aceito 
    Resultado.setText(r);// Camppo de resposta recebendo valor 
        
    }//GEN-LAST:event_DivisãoActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
 
    
        
    }//GEN-LAST:event_NovoActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed

 N1.setText("");
 N2.setText("");
 Resultado.setText("");

    }//GEN-LAST:event_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comparação;
    private javax.swing.JButton Divisão;
    private javax.swing.JButton Limpar;
    private javax.swing.JButton Mutiplicação;
    private javax.swing.JTextField N1;
    private javax.swing.JTextField N2;
    private javax.swing.JButton Novo;
    private javax.swing.JLabel Numero1;
    private javax.swing.JLabel Numero2;
    private javax.swing.JTextField Resultadado;
    private javax.swing.JLabel Resultado;
    private javax.swing.JButton Sair;
    private javax.swing.JButton Soma;
    private javax.swing.JButton Subtração;
    private javax.swing.JButton jButton9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static class txt_n2 {

        public txt_n2() {
        }
    }
}
